Repository GDSC-JSCOE/Demo-hacktoberfest, pull requests merged in 2022-09, with the labels that each got.

#1 Update Test.txt
  Test.txt
Labels: hacktober-accepted

#2 Update Test.txt
  Test.txt
Labels: hacktober-accepted, hacktoberfest-accepted

#11 Create Print.py
  Print.py
Labels: hacktoberfest-accepted

#10 Aman wrote his favorite cricket player
  Test.txt
Labels: hacktoberfest-accepted
